#!/usr/bin/env python3
"""Build POD book covers (front cover + full wrap) for US and EU editions.

Usage:
  python3 tmp/build_book_cover.py --edition us     # US front cover
  python3 tmp/build_book_cover.py --edition eu     # EU front cover
  python3 tmp/build_book_cover.py --edition all    # Both editions
  python3 tmp/build_book_cover.py --edition us --wrap  # Full wrap (back+spine+front)

The cover image will be cropped/positioned automatically.
TODO: Replace low-res placeholder with high-res image when available.
"""

import argparse
import os
import subprocess
import shutil
from PIL import Image

# Paths
COVER_IMAGE = "/home/jeltz/nuc/sites/matthiasgruber.com/photos/art-consciousness.jpg"
OUTPUT_DIR = "/home/jeltz/aIware/pop-sci"
FIGURES_DIR = "/home/jeltz/aIware/figures"

# Bleed: 0.125" on each side (KDP/IngramSpark standard)
BLEED = 0.125

# Edition configs
EDITIONS = {
    "us": {
        "label": "US Trade 6\"×9\"",
        "trim_w": 6.0,   # inches
        "trim_h": 9.0,
        "pages": 249,
        "paper_thickness": 0.002252,  # white paper (KDP)
        "suffix": "",
    },
    "eu": {
        "label": "European 15.5×23cm",
        "trim_w": 155 / 25.4,  # 6.102"
        "trim_h": 230 / 25.4,  # 9.055"
        "pages": 243,
        "paper_thickness": 0.002252,  # white paper
        "suffix": "-eu",
    },
}

BACK_COVER_BLURB = r"""You are a simulation.

Not a metaphor. Not a philosophical thought experiment. A literal, running simulation ---
generated by your brain, updated hundreds of times per second, experienced from the inside.

This book presents a unified theory of consciousness built on four models the brain maintains:
two of the world (one learned, one simulated) and two of the self (one learned, one simulated).
The theory dissolves the ``hard problem,'' explains psychedelic phenomenology, predicts
nine testable outcomes, and provides a concrete blueprint for building a conscious machine.

If the theory is right, consciousness was never mysterious. It was just mislabeled."""

BACK_COVER_TAGLINE = r"""\textit{``The most ambitious theory of consciousness I've encountered\\from outside the academy.''} --- Review pending"""


def crop_for_front_cover(img, trim_w, trim_h, dpi=300):
    """Crop the image for front cover, focusing on the right side (neural eye)."""
    target_w = int((trim_w + 2 * BLEED) * dpi)
    target_h = int((trim_h + 2 * BLEED) * dpi)

    img_w, img_h = img.size

    # Scale to fill height
    scale = target_h / img_h
    scaled_w = int(img_w * scale)
    scaled_h = target_h
    img_scaled = img.resize((scaled_w, scaled_h), Image.LANCZOS)

    # Crop from the right side (neural eye focal point)
    # Position the eye roughly at the right third of the cover
    right_edge = scaled_w
    left_edge = right_edge - target_w
    if left_edge < 0:
        left_edge = 0
        right_edge = target_w

    return img_scaled.crop((left_edge, 0, right_edge, scaled_h))


def crop_for_wrap(img, total_w_in, trim_h, dpi=300):
    """Crop the image for full wrap (back + spine + front)."""
    target_w = int((total_w_in + 2 * BLEED) * dpi)
    target_h = int((trim_h + 2 * BLEED) * dpi)

    img_w, img_h = img.size

    # Scale to fill height
    scale = target_h / img_h
    scaled_w = int(img_w * scale)
    scaled_h = target_h
    img_scaled = img.resize((scaled_w, scaled_h), Image.LANCZOS)

    # Center crop for wrap
    left = max(0, (scaled_w - target_w) // 2)
    return img_scaled.crop((left, 0, left + target_w, scaled_h))


def build_front_cover_tex(edition):
    """Generate LaTeX for front cover."""
    ed = EDITIONS[edition]
    cover_w = ed["trim_w"] + 2 * BLEED
    cover_h = ed["trim_h"] + 2 * BLEED
    img_name = f"cover-front{ed['suffix']}.jpg"

    return r"""\documentclass[border=0pt]{standalone}
\usepackage[T1]{fontenc}
\usepackage{palatino}
\usepackage{graphicx}
\usepackage{tikz}
\usepackage{xcolor}

\begin{document}
\begin{tikzpicture}

% Black background (eliminates any edge gaps from rounding)
\fill[black] (0,0) rectangle (""" + f"{cover_w}" + r"""in, """ + f"{cover_h}" + r"""in);

% Background image (full bleed)
\node[inner sep=0pt, outer sep=0pt] at (""" + f"{cover_w/2}" + r"""in, """ + f"{cover_h/2}" + r"""in) {
  \includegraphics[width=""" + f"{cover_w}" + r"""in, height=""" + f"{cover_h}" + r"""in]{""" + img_name + r"""}
};

% Dark gradient overlay at top — covers title + subtitle, fades before neural eye
\fill[top color=black!90, bottom color=black!0, opacity=0.70]
  (0in, """ + f"{cover_h * 0.68}" + r"""in)
  rectangle (""" + f"{cover_w}" + r"""in, """ + f"{cover_h}" + r"""in);

% Subtle dark gradient at bottom for author name
\fill[bottom color=black!80, top color=black!0, opacity=0.65]
  (0in, 0in)
  rectangle (""" + f"{cover_w}" + r"""in, """ + f"{BLEED + 1.2}" + r"""in);

% Title
\node[anchor=north, text=white, font=\fontsize{36}{42}\selectfont\bfseries,
      text width=""" + f"{ed['trim_w'] - 1.0}" + r"""in, align=center]
  at (""" + f"{cover_w/2}" + r"""in, """ + f"{cover_h - BLEED - 0.6}" + r"""in)
  {The Simulation\\[0.15in] You Call ``I''};

% Subtitle (tucked close under title, within gradient zone)
\node[anchor=north, text=white!90, font=\fontsize{14}{18}\selectfont,
      text width=""" + f"{ed['trim_w'] - 1.2}" + r"""in, align=center]
  at (""" + f"{cover_w/2}" + r"""in, """ + f"{cover_h - BLEED - 2.2}" + r"""in)
  {The Architecture of Consciousness,\\Computation, and the Cosmos};

% Author name
\node[anchor=south, text=white!95, font=\fontsize{18}{22}\selectfont]
  at (""" + f"{cover_w/2}" + r"""in, """ + f"{BLEED + 0.5}" + r"""in)
  {Matthias Gruber};

\end{tikzpicture}
\end{document}
"""


def build_wrap_tex(edition):
    """Generate LaTeX for full wrap (back + spine + front)."""
    ed = EDITIONS[edition]
    spine_w = ed["pages"] * ed["paper_thickness"]
    total_w = ed["trim_w"] * 2 + spine_w + 2 * BLEED
    total_h = ed["trim_h"] + 2 * BLEED
    img_name = f"cover-wrap{ed['suffix']}.jpg"

    # Key positions (from left)
    back_center_x = BLEED + ed["trim_w"] / 2
    spine_center_x = BLEED + ed["trim_w"] + spine_w / 2
    front_center_x = BLEED + ed["trim_w"] + spine_w + ed["trim_w"] / 2
    barcode_x = BLEED + ed["trim_w"] - 1.2  # bottom-right of back cover
    barcode_y = BLEED + 0.5

    return r"""\documentclass[border=0pt]{standalone}
\usepackage[T1]{fontenc}
\usepackage{palatino}
\usepackage{graphicx}
\usepackage{tikz}
\usepackage{xcolor}

\begin{document}
\begin{tikzpicture}

% Black background
\fill[black] (0,0) rectangle (""" + f"{total_w}" + r"""in, """ + f"{total_h}" + r"""in);

% Background image (full bleed)
\node[inner sep=0pt, outer sep=0pt] at (""" + f"{total_w/2}" + r"""in, """ + f"{total_h/2}" + r"""in) {
  \includegraphics[width=""" + f"{total_w}" + r"""in, height=""" + f"{total_h}" + r"""in]{""" + img_name + r"""}
};

% ---- FRONT COVER (right side) ----

% Dark gradient at top — covers title + subtitle, fades before neural eye
\fill[top color=black!90, bottom color=black!0, opacity=0.70]
  (""" + f"{BLEED + ed['trim_w'] + spine_w}" + r"""in, """ + f"{total_h * 0.68}" + r"""in)
  rectangle (""" + f"{total_w}" + r"""in, """ + f"{total_h}" + r"""in);

% Gradient at bottom for author
\fill[bottom color=black!80, top color=black!0, opacity=0.65]
  (""" + f"{BLEED + ed['trim_w'] + spine_w}" + r"""in, 0in)
  rectangle (""" + f"{total_w}" + r"""in, """ + f"{BLEED + 1.2}" + r"""in);

% Front title
\node[anchor=north, text=white, font=\fontsize{36}{42}\selectfont\bfseries,
      text width=""" + f"{ed['trim_w'] - 1.0}" + r"""in, align=center]
  at (""" + f"{front_center_x}" + r"""in, """ + f"{total_h - BLEED - 0.6}" + r"""in)
  {The Simulation\\[0.15in] You Call ``I''};

% Front subtitle (within gradient zone)
\node[anchor=north, text=white!90, font=\fontsize{14}{18}\selectfont,
      text width=""" + f"{ed['trim_w'] - 1.2}" + r"""in, align=center]
  at (""" + f"{front_center_x}" + r"""in, """ + f"{total_h - BLEED - 2.2}" + r"""in)
  {The Architecture of Consciousness,\\Computation, and the Cosmos};

% Front author
\node[anchor=south, text=white!95, font=\fontsize{18}{22}\selectfont]
  at (""" + f"{front_center_x}" + r"""in, """ + f"{BLEED + 0.5}" + r"""in)
  {Matthias Gruber};

% ---- SPINE ----

% Dark overlay on spine for readability
\fill[black, opacity=0.5]
  (""" + f"{BLEED + ed['trim_w']}" + r"""in, 0in)
  rectangle (""" + f"{BLEED + ed['trim_w'] + spine_w}" + r"""in, """ + f"{total_h}" + r"""in);

% Spine text (rotated)
\node[rotate=270, text=white, font=\fontsize{10}{12}\selectfont\bfseries,
      anchor=center]
  at (""" + f"{spine_center_x}" + r"""in, """ + f"{total_h/2 + 0.5}" + r"""in)
  {The Simulation You Call ``I''};

\node[rotate=270, text=white!90, font=\fontsize{8}{10}\selectfont,
      anchor=center]
  at (""" + f"{spine_center_x}" + r"""in, """ + f"{total_h/2 - 1.5}" + r"""in)
  {Matthias Gruber};

% ---- BACK COVER (left side) ----

% Dark overlay on back cover for text
\fill[black, opacity=0.55]
  (""" + f"{BLEED}" + r"""in, """ + f"{BLEED}" + r"""in)
  rectangle (""" + f"{BLEED + ed['trim_w']}" + r"""in, """ + f"{total_h - BLEED}" + r"""in);

% Back cover blurb
\node[anchor=north, text=white!95, font=\fontsize{11}{15}\selectfont,
      text width=""" + f"{ed['trim_w'] - 1.4}" + r"""in, align=left]
  at (""" + f"{back_center_x}" + r"""in, """ + f"{total_h - BLEED - 1.0}" + r"""in)
  {""" + BACK_COVER_BLURB + r"""};

% Barcode placeholder
\draw[white, thick] (""" + f"{barcode_x - 0.8}" + r"""in, """ + f"{barcode_y - 0.2}" + r"""in)
  rectangle (""" + f"{barcode_x + 0.8}" + r"""in, """ + f"{barcode_y + 0.8}" + r"""in);
\node[text=white!70, font=\footnotesize] at (""" + f"{barcode_x}" + r"""in, """ + f"{barcode_y + 0.3}" + r"""in)
  {ISBN BARCODE};

\end{tikzpicture}
\end{document}
"""


def build_cover(edition, wrap=False):
    """Build a cover for the given edition."""
    ed = EDITIONS[edition]
    suffix = ed["suffix"]
    spine_w = ed["pages"] * ed["paper_thickness"]

    print(f"\n{'='*60}")
    kind = "full wrap" if wrap else "front cover"
    print(f"Building {kind}: {ed['label']}")
    print(f"  Spine width: {spine_w:.3f}\" ({ed['pages']} pages × {ed['paper_thickness']})")
    print(f"{'='*60}")

    # Load and crop the image
    img = Image.open(COVER_IMAGE)
    print(f"  Source image: {img.size[0]}×{img.size[1]} px")

    if wrap:
        total_w = ed["trim_w"] * 2 + spine_w
        cropped = crop_for_wrap(img, total_w, ed["trim_h"])
        img_name = f"cover-wrap{suffix}.jpg"
        tex_content = build_wrap_tex(edition)
        tex_name = f"cover-wrap{suffix}.tex"
    else:
        cropped = crop_for_front_cover(img, ed["trim_w"], ed["trim_h"])
        img_name = f"cover-front{suffix}.jpg"
        tex_content = build_front_cover_tex(edition)
        tex_name = f"cover-front{suffix}.tex"

    # Save cropped image
    img_path = os.path.join(OUTPUT_DIR, img_name)
    cropped.save(img_path, quality=95)
    print(f"  Cropped image: {cropped.size[0]}×{cropped.size[1]} px → {img_name}")

    # Write LaTeX
    tex_path = os.path.join(OUTPUT_DIR, tex_name)
    with open(tex_path, 'w') as f:
        f.write(tex_content)

    # Compile
    print("  Compiling PDF...")
    result = subprocess.run(
        ['pdflatex', '-interaction=nonstopmode', '-output-directory', OUTPUT_DIR, tex_path],
        capture_output=True, cwd=OUTPUT_DIR, timeout=60
    )

    pdf_name = tex_name.replace('.tex', '.pdf')
    pdf_path = os.path.join(OUTPUT_DIR, pdf_name)
    if os.path.exists(pdf_path):
        size_kb = os.path.getsize(pdf_path) / 1024
        print(f"  SUCCESS: {pdf_path} ({size_kb:.0f} KB)")

        # Copy to Windows desktop
        win_path = f"/mnt/c/Users/Matthias/Desktop/{pdf_name}"
        try:
            shutil.copy2(pdf_path, win_path)
            print(f"  Copied to: {win_path}")
        except Exception as e:
            print(f"  Note: Could not copy to desktop: {e}")
        return True
    else:
        print("  FAILED")
        log_path = tex_path.replace('.tex', '.log')
        if os.path.exists(log_path):
            with open(log_path, 'r', errors='replace') as f:
                log = f.read()
            errors = [l for l in log.split('\n') if l.startswith('!')]
            for e in errors[:10]:
                print(f"  ERROR: {e}")
        return False


def main():
    parser = argparse.ArgumentParser(description="Build POD book covers")
    parser.add_argument('--edition', choices=['us', 'eu', 'all'], default='us',
                        help='Edition: us, eu, or all')
    parser.add_argument('--wrap', action='store_true',
                        help='Build full wrap (back+spine+front) instead of front cover only')
    args = parser.parse_args()

    editions = ['us', 'eu'] if args.edition == 'all' else [args.edition]
    results = {}
    for ed in editions:
        results[ed] = build_cover(ed, wrap=args.wrap)

    print(f"\n{'='*60}")
    for ed, ok in results.items():
        status = "OK" if ok else "FAILED"
        print(f"  {EDITIONS[ed]['label']}: {status}")
    print(f"{'='*60}")


if __name__ == '__main__':
    main()
