#!/usr/bin/env python3
"""
Generate an HTML review page for Session 55 book manuscript changes.
Shows each change with old/new text, labels, and navigation.
"""

import html as html_mod

# Each change: (id, description, location, old_text, new_text, change_type)
CHANGES = [
    ("C25", "Medicine → neurology parenthetical",
     "About the Author (~L107)",
     "after abandoning medicine at the University of Innsbruck",
     "after abandoning medicine at the University of Innsbruck (a subject I had originally chosen in order to study neurology)",
     "Addition"),

    ("C35", "Blind spot proof + field consensus",
     "Chapter 1 (~L187)",
     "This is the starting point of the Four-Model Theory. It begins with the observation that you have never, in your entire life, directly experienced reality. You have experienced a simulation of reality, generated by your brain, so seamlessly that you have never suspected the difference. And it argues that this observation, taken seriously, dissolves the Hard Problem.",
     "This is the starting point of the Four-Model Theory. It begins with the observation that you have never, in your entire life, directly experienced reality. Consider the simplest proof: you have a blind spot in each eye — a region of the retina with no photoreceptors at all, where the optic nerve exits — yet you see no hole. Your brain fills it in with fabricated content. If perception were direct access to reality, you would see two dark patches. You don't, because you are looking at a model. This claim, incidentally, is not controversial — that perception is constructive rather than direct is mainstream neuroscience, accepted by virtually every researcher in the field. You have experienced a simulation of reality, generated by your brain, so seamlessly that you have never suspected the difference. And the theory argues that this observation, taken seriously, dissolves the Hard Problem.",
     "New paragraph (blind spot example + field consensus)"),

    ("C36", 'Fix "But first" transition',
     "Chapter 1 (~L207)",
     "But first, I need to show you the four models.",
     "Now it's time to look at the four models.",
     "Rewording"),

    ("C37", "Forward reference to Ch.1 argument",
     "Chapter 2 (~L223)",
     "This is uncontroversial neuroscience. Every neuroscientist",
     "As I argued in Chapter 1, this is uncontroversial neuroscience. Every neuroscientist",
     "Addition (callback to blind spot)"),

    ("C39", "Connectome research reference",
     "Chapter 2 (~L295)",
     "Reading the virtual side from the real side is a future research programme — one that the theory defines clearly but cannot execute yet.",
     "Reading the virtual side from the real side is a future research programme — one that the theory defines clearly but cannot execute yet. However, the foundation for that programme is already being laid. The Human Connectome Project and related efforts are mapping the brain's wiring at increasingly fine resolution. We cannot yet decode the virtual side from structural data — but the structural data is coming.",
     "New sentences"),

    ("C40", "Birds (corvids/parrots) as alternative architecture",
     "Chapter 2 (~L341)",
     "The octopus, with its radically distributed nervous system — eight semi-autonomous arms, each with its own neural processing center containing roughly 40 million neurons — represents a completely different architectural approach that may achieve equivalent computational power. If what matters",
     "The octopus, with its radically distributed nervous system — eight semi-autonomous arms, each with its own neural processing center containing roughly 40 million neurons — represents a completely different architectural approach that may achieve equivalent computational power. Birds offer another striking example: corvids and parrots lack a layered cortex entirely, their pallium organized into nuclear clusters rather than sheets — yet crows make tools, plan for the future, and arguably recognize themselves in mirrors. If what matters",
     "New sentence"),

    ("C41", 'Fix "interesting/boring" contradiction',
     "Chapter 5 (~L609)",
     "Interesting, well-supported, and — forgive me — the boring one.",
     "Well-established, thoroughly documented, and — forgive me — the boring one.",
     "Rewording"),

    ("C43", 'Add "(or produces a hologram)"',
     "Chapter 5 (~L613)",
     "Not a system that merely *runs on* a holographic substrate.",
     "Not a system that merely *runs on* a holographic substrate (or produces a hologram).",
     "Parenthetical"),

    ("C46", "Expand learning with adaptation + override",
     "Chapter 10 (~L969)",
     "The answer is learning. Specifically, a kind of learning that unconscious systems simply cannot do.",
     "The answer is learning — and with it, adaptation and the ability to act against learned behavior. Specifically, a kind of learning that unconscious systems simply cannot do.",
     "Addition"),

    ("C48", "Continuity value argument (stroke/amnesia)",
     "Chapter 13 (~L1191)",
     "A mind upload that gets the proteomic level wrong gives you a conscious being, perhaps, but not the person you were trying to copy.",
     "A mind upload that gets the proteomic level wrong gives you a conscious being, perhaps, but not the person you were trying to copy. Yet even an imperfect copy retains value. Consider stroke survivors or amnesia patients: their personal continuity has been significantly disrupted — memories lost, personality altered, cognitive abilities changed — and yet most of them maintain that something essential persists. Imperfect continuity, it turns out, is vastly preferable to no continuity at all. A transfer that preserves 90% of someone's connectome is not a failure — it's a different category of success, and for many people, preferable to death.",
     "New paragraph"),

    ("C52", '"Depending how it is done" qualifier',
     "Chapter 13 (~L1255)",
     "Instant transfer, though — scanning, copying, booting on a new substrate — would hit the simulation with all the changes at once. And that, I think, is where the danger lives.",
     "Instant transfer, though — scanning, copying, booting on a new substrate — would hit the simulation with all the changes at once. How severe the impact would be depends entirely on the method: a transfer to a robot body with rich sensory input would fare better than one to a disembodied server. But in either case, that sudden discontinuity is where the danger lives.",
     "Rewording + new sentence"),

    ("C53", "Bobiverse series reference",
     "Chapter 13 (~L1259)",
     "The legal and ethical frameworks required to manage this don't exist and can't be improvised. They need to be built with the same care as the technology itself.",
     "The legal and ethical frameworks required to manage this don't exist and can't be improvised. They need to be built with the same care as the technology itself. (Dennis E. Taylor's *Bobiverse* series — starting with *We Are Legion (We Are Bob)*, 2016 — explores this scenario with surprising philosophical depth beneath its comedic surface. If you want to feel what the copy problem might be like from the inside, start there.)",
     "Parenthetical (book reference)"),

    ("C55", "Cosmic argument expansions (scale, infinity, nothing)",
     "Chapter 14 (~L1347)",
     "And a computational substrate of this universe's scale — vast if not infinite in space, time, and possibly dimensions we haven't identified — doesn't merely *allow* self-simulating systems to emerge. It guarantees it. Not as a matter of luck, not as a roll of cosmic dice that happened to come up consciousness. As a structural consequence of what this universe *is*. The remaining mystery is one level deeper: why is there a Class 4-capable universe at all? That, I genuinely don't know. But the jump from \"Class 4-capable universe\" to \"conscious beings asking why they're conscious\" — that part follows from the architecture.",
     "And a computational substrate of this universe's scale — vast if not infinite in space, time, possibly scale, and perhaps dimensions we haven't identified — doesn't merely *allow* self-simulating systems to emerge. It almost guarantees it, at least if the universe is infinite in some of these dimensions. Not as a matter of luck, not as a roll of cosmic dice that happened to come up consciousness, but as a structural consequence of what this universe *is*. The remaining mystery is one level deeper: why is there a Class 4-capable universe at all? That, I genuinely don't know — though one might suspect the question is malformed, since \"nothing\" is arguably a Platonic abstraction rather than a possible state of affairs, and whatever exists must have *some* computational character. But the jump from \"Class 4-capable universe\" to \"conscious beings asking why they're conscious\" — that part follows from the architecture.",
     "Rewording + new clause"),
]

POSTPONED = [
    ("C33", "Metzinger's theory status since 2015", "About the Author", "Needs research into current state of SMT"),
    ("C34", "Mathematics has harder problems", "Chapter 1", "Needs author decision — already softened by A1, how much further to hedge?"),
    ("C38", "Replace figure + restructure four-models intro", "Chapter 2", "Major structural rewrite — figure choice, two-vs-four framing, digital twin analogy"),
    ("C42", "d'Hooft holographic universe question", "Chapter 5", "Needs decision — powerful connection to 't Hooft's CA interpretation but speculative"),
    ("C44", "Lucid dreaming appendix", "New Appendix D", "Major new content — practical techniques (reality checks, MILD, WILD)"),
    ("C45", "Split-brain = two persons argument", "Chapter 8", "Important theoretical claim — needs philosophical treatment (Parfit, Nagel)"),
    ("C47", "LLM-breaking prompt experiment", "Chapter 11", "Needs experimental validation before book inclusion"),
    ("C49", "Virtual-level-only copy theory", "Chapter 13", "Careful treatment needed — EWM+ESM transfer without substrate"),
    ("C50", "Brain 'programming language' decoding", "Chapter 13", "Speculative — reverse-engineering neural code for digital recompilation"),
    ("C51", "Major copy problem meditation", "Chapter 13", "Large new subsection — sleep interruption, birth identity, personal experience"),
    ("C54", "Expanded salvia experience", "Chapter 6", "Needs chronology verification (NDE 1998/99 vs salvia), salvinorin A synthesis claim"),
    ("C56", "Crick/Koch NCC reference", "Appendix A", "Author must confirm: Koch's *Quest for Consciousness* or Crick's *Astonishing Hypothesis*?"),
]


def diff_texts(old, new):
    """Simple word-level diff highlighting. Returns (old_html, new_html)."""
    old_words = old.split()
    new_words = new.split()

    # Find longest common prefix
    prefix_len = 0
    for i in range(min(len(old_words), len(new_words))):
        if old_words[i] == new_words[i]:
            prefix_len = i + 1
        else:
            break

    # Find longest common suffix (after prefix)
    suffix_len = 0
    for i in range(1, min(len(old_words) - prefix_len, len(new_words) - prefix_len) + 1):
        if old_words[-i] == new_words[-i]:
            suffix_len = i
        else:
            break

    # Build highlighted versions
    old_mid = old_words[prefix_len:len(old_words) - suffix_len if suffix_len else len(old_words)]
    new_mid = new_words[prefix_len:len(new_words) - suffix_len if suffix_len else len(new_words)]
    prefix = old_words[:prefix_len]
    suffix = old_words[len(old_words) - suffix_len:] if suffix_len else []

    def esc(words):
        return html_mod.escape(' '.join(words))

    old_html = ''
    new_html = ''

    if prefix:
        old_html += f'<span class="unchanged">{esc(prefix)} </span>'
        new_html += f'<span class="unchanged">{esc(prefix)} </span>'

    if old_mid:
        old_html += f'<span class="removed-text">{esc(old_mid)}</span>'
    if new_mid:
        new_html += f'<span class="added-text">{esc(new_mid)}</span>'

    if suffix:
        old_html += f' <span class="unchanged">{esc(suffix)}</span>'
        new_html += f' <span class="unchanged">{esc(suffix)}</span>'

    return old_html, new_html


def render_change(cid, desc, location, old_text, new_text, change_type):
    """Render a single change block."""
    old_html, new_html = diff_texts(old_text, new_text)

    return f'''<div class="change-block" id="change-{cid}">
  <div class="change-header">
    <span class="change-id">{cid}</span>
    <span class="change-desc">{html_mod.escape(desc)}</span>
    <span class="change-type">{html_mod.escape(change_type)}</span>
    <span class="change-loc">{html_mod.escape(location)}</span>
  </div>
  <div class="old-block">
    <div class="block-label">OLD</div>
    <div class="text-content">{old_html}</div>
  </div>
  <div class="new-block">
    <div class="block-label">NEW</div>
    <div class="text-content">{new_html}</div>
  </div>
</div>'''


def main():
    nav_links = '\n    '.join(
        f'<a href="#change-{cid}">{cid}</a>' for cid, *_ in CHANGES
    )

    change_blocks = '\n\n'.join(
        render_change(*c) for c in CHANGES
    )

    summary_rows = '\n'.join(
        f'<tr><td>{cid}</td><td>{html_mod.escape(desc)}</td>'
        f'<td>{html_mod.escape(loc)}</td><td>{html_mod.escape(ctype)}</td></tr>'
        for cid, desc, loc, _, _, ctype in CHANGES
    )

    postponed_rows = '\n'.join(
        f'<tr><td>{cid}</td><td>{html_mod.escape(desc)}</td>'
        f'<td>{html_mod.escape(loc)}</td><td>{html_mod.escape(reason)}</td></tr>'
        for cid, desc, loc, reason in POSTPONED
    )

    page = f'''<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<title>Book Manuscript — Session 55 Changes Review</title>
<style>
  * {{ box-sizing: border-box; }}
  body {{
    max-width: 920px;
    margin: 40px auto;
    padding: 0 24px 80px;
    font-family: Georgia, 'Times New Roman', serif;
    font-size: 15px;
    line-height: 1.75;
    color: #222;
    background: #fafafa;
  }}
  h1 {{ font-size: 1.6em; margin-top: 1.5em; }}
  h2 {{ font-size: 1.3em; margin-top: 2em; border-bottom: 1px solid #ccc; padding-bottom: 0.3em; }}
  p {{ text-align: justify; }}

  .nav-bar {{
    position: fixed;
    top: 0; left: 0; right: 0;
    background: #1565c0;
    color: white;
    padding: 8px 20px;
    font-family: 'Helvetica Neue', Arial, sans-serif;
    font-size: 0.82em;
    z-index: 100;
    display: flex;
    align-items: center;
    gap: 8px;
    flex-wrap: wrap;
    box-shadow: 0 2px 8px rgba(0,0,0,0.15);
  }}
  .nav-bar .title {{ font-weight: bold; margin-right: auto; font-size: 1.1em; white-space: nowrap; }}
  .nav-bar a {{
    color: white;
    text-decoration: none;
    background: rgba(255,255,255,0.15);
    padding: 3px 10px;
    border-radius: 4px;
    font-weight: 500;
    white-space: nowrap;
  }}
  .nav-bar a:hover {{ background: rgba(255,255,255,0.3); }}
  body {{ padding-top: 55px; }}

  .change-block {{
    margin: 2em 0;
    border: 1px solid #bbb;
    border-radius: 8px;
    overflow: hidden;
    box-shadow: 0 1px 6px rgba(0,0,0,0.07);
  }}
  .change-header {{
    background: #1565c0;
    color: white;
    padding: 10px 16px;
    font-family: 'Helvetica Neue', Arial, sans-serif;
    font-size: 0.88em;
    display: flex;
    gap: 12px;
    align-items: center;
    flex-wrap: wrap;
  }}
  .change-id {{
    background: rgba(255,255,255,0.25);
    padding: 2px 10px;
    border-radius: 4px;
    font-weight: bold;
  }}
  .change-desc {{ flex: 1; min-width: 200px; }}
  .change-type {{
    background: rgba(255,255,255,0.12);
    padding: 2px 8px;
    border-radius: 3px;
    font-size: 0.9em;
    opacity: 0.9;
  }}
  .change-loc {{
    opacity: 0.8;
    font-style: italic;
    font-size: 0.9em;
  }}

  .old-block, .new-block {{
    padding: 14px 18px;
    position: relative;
  }}
  .old-block {{
    background: #fce4ec;
    border-bottom: 1px solid #e0e0e0;
  }}
  .new-block {{
    background: #e8f5e9;
  }}
  .block-label {{
    position: absolute;
    top: 8px; right: 14px;
    font-family: 'Helvetica Neue', Arial, sans-serif;
    font-size: 0.68em;
    font-weight: bold;
    letter-spacing: 0.5px;
    padding: 2px 10px;
    border-radius: 3px;
    color: white;
  }}
  .old-block .block-label {{ background: #c62828; }}
  .new-block .block-label {{ background: #2e7d32; }}

  .text-content {{
    font-size: 0.95em;
    padding-right: 50px;
  }}
  .unchanged {{ color: #666; }}
  .removed-text {{
    color: #b71c1c;
    background: #ffcdd2;
    padding: 1px 3px;
    border-radius: 2px;
    text-decoration: line-through;
    text-decoration-color: #e57373;
  }}
  .added-text {{
    color: #1b5e20;
    background: #c8e6c9;
    padding: 1px 3px;
    border-radius: 2px;
  }}

  table {{
    border-collapse: collapse;
    font-size: 0.88em;
    width: 100%;
    font-family: 'Helvetica Neue', Arial, sans-serif;
  }}
  th, td {{
    border: 1px solid #ccc;
    padding: 8px 12px;
    text-align: left;
    vertical-align: top;
  }}
  .summary th {{ background: #e3f2fd; }}
  .postponed th {{ background: #fff3e0; }}
  tr:nth-child(even) {{ background: #f8f8f8; }}

  .intro-box {{
    background: #e3f2fd;
    border: 1px solid #90caf9;
    border-radius: 6px;
    padding: 14px 18px;
    margin: 1.5em 0;
    font-family: 'Helvetica Neue', Arial, sans-serif;
    font-size: 0.92em;
  }}
  .intro-box strong {{ color: #1565c0; }}

  @media print {{
    .nav-bar {{ display: none; }}
    body {{ padding-top: 0; max-width: none; }}
    .change-block {{ break-inside: avoid; }}
  }}
</style>
</head>
<body>

<div class="nav-bar">
  <span class="title">Session 55 — Book Changes</span>
  {nav_links}
</div>

<h1>Book Manuscript — Session 55 Proposed Changes</h1>

<div class="intro-box">
  <strong>13 changes</strong> from Category C applied to <code>pop-sci/book-manuscript.md</code>.<br>
  Word count: 45,018 &rarr; 45,539 (+521 words).<br><br>
  Each change shows old text with <span class="removed-text">red strikethrough</span>
  and new text in <span class="added-text">green highlight</span>.
  Unchanged context appears in <span class="unchanged">grey</span>.<br><br>
  <strong>To revert any change:</strong> note its ID (e.g. C35) and tell me next session.
</div>

<h2>Proposed Changes (13)</h2>

{change_blocks}

<h2>Postponed for Next Session (12 items)</h2>

<p>These require discussion, research, structural decisions, or major new content.</p>

<div class="postponed">
<table>
<tr><th>ID</th><th>Description</th><th>Location</th><th>Why Postponed</th></tr>
{postponed_rows}
</table>
</div>

<h2>Change Summary</h2>

<div class="summary">
<table>
<tr><th>ID</th><th>Description</th><th>Location</th><th>Type</th></tr>
{summary_rows}
</table>
</div>

</body>
</html>'''

    output = '/home/jeltz/aIware/tmp/book-changes-review.html'
    with open(output, 'w') as f:
        f.write(page)
    print(f"Written to: {output}")
    print(f"Size: {len(page):,} bytes")
    print(f"Changes: {len(CHANGES)}")
    print(f"Postponed: {len(POSTPONED)}")


if __name__ == '__main__':
    main()
